---
version: 2

# ====================
# WORKFLOW DECLARATION
# ====================
workflows:
  version: 2
  main:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - release:
          requires:
            - build
            - lint
          # filters:
          #   branches:
          #     only:
          #       - master

# ====================
# SHARED JOBS POINTERS
# ====================
restore_cache: &restore_cache
  restore_cache:
    keys:
      - dependencies-{{ checksum "package.json" }}
      - dependencies-

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules/
    key: dependencies-{{ checksum "package.json" }}

install_dependencies: &install_dependencies
  run:
    name: Install dependencies.
    command: yarn -s --no-progress

# ================
# JOB DECLARATIONS
# ================
jobs:

  install_dependencies:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run linter.
          command: yarn lint

  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Transpile sources.
          command: yarn build
      - *save_cache

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - run: yarn semantic-release
